**Tytuł:** Krótkie streszczenie zadania  

**Opis:**
- Co należy zrobić
- Dlaczego to robimy
- Zależności lub wymagania techniczne

**Powiązana User Story:** #12  
**Definition of Done / Kryteria akceptacji:**
- [ ] Warunek 1
- [ ] Warunek 2
- [ ] Warunek 3

**Osoba odpowiedzialna:** @login  
**Szacowany czas:** 4h
